"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { FileText, Sparkles, Clock, Share2 } from "lucide-react";
import ReactMarkdown from "react-markdown";
import { fmtCurrency, fmtDateTime, ratingLabel, RATING_COLORS } from "@/lib/format";
import { toast } from "sonner";

interface Report {
  id: string;
  title: string;
  type: string;
  rating: string | null;
  priceTarget: number | null;
  summary: string | null;
  status: string;
  createdAt: string;
  content?: string;
  company: { id: string; ticker: string; name: string; sector: string | null };
}

export function ReportsView({ onOpenCompany }: { onOpenCompany: (id: string) => void }) {
  const [activeReport, setActiveReport] = useState<Report | null>(null);

  const { data, isLoading } = useQuery({
    queryKey: ["reports-all"],
    queryFn: async () => {
      const res = await fetch("/api/reports?limit=50");
      return res.json() as Promise<{ reports: Report[] }>;
    },
  });

  const reports = data?.reports ?? [];

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-2xl font-bold tracking-tight">Research Reports</h1>
        <p className="text-sm text-muted-foreground">
          Institutional-grade reports generated by the autonomous AI research engine.
        </p>
      </div>

      {isLoading ? (
        <div className="space-y-2">
          {Array.from({ length: 6 }).map((_, i) => (
            <Skeleton key={i} className="h-20" />
          ))}
        </div>
      ) : reports.length === 0 ? (
        <Card>
          <CardContent className="flex flex-col items-center justify-center py-16 text-center">
            <FileText className="mb-3 h-10 w-10 text-muted-foreground" />
            <div className="font-medium">No reports yet</div>
            <p className="mt-1 max-w-md text-sm text-muted-foreground">
              Open a company and click “Generate report” to produce your first AI research report.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid grid-cols-1 gap-3 md:grid-cols-2 lg:grid-cols-3">
          {reports.map((r) => (
            <Card
              key={r.id}
              className="cursor-pointer transition-shadow hover:shadow-md"
              onClick={() => openReport(r)}
            >
              <CardHeader className="pb-2">
                <div className="flex items-start gap-2">
                  <div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-md bg-primary/10 text-primary">
                    <FileText className="h-4 w-4" />
                  </div>
                  <div className="min-w-0 flex-1">
                    <CardTitle className="line-clamp-2 text-sm font-semibold leading-tight">
                      {r.title}
                    </CardTitle>
                    <CardDescription className="mt-1 flex items-center gap-1.5 text-xs">
                      <span className="font-mono">{r.company.ticker}</span>
                      <span>·</span>
                      <Clock className="h-3 w-3" />
                      {fmtDateTime(r.createdAt)}
                    </CardDescription>
                  </div>
                </div>
              </CardHeader>
              <CardContent className="space-y-2">
                {r.summary && (
                  <p className="line-clamp-2 text-xs text-muted-foreground">{r.summary}</p>
                )}
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Badge variant="secondary" className="text-[10px] uppercase">{r.type}</Badge>
                    {r.rating && (
                      <Badge variant="outline" className={`text-[10px] ${RATING_COLORS[r.rating]}`}>
                        {ratingLabel(r.rating)}
                      </Badge>
                    )}
                  </div>
                  {r.priceTarget && (
                    <div className="text-right text-xs">
                      <span className="text-muted-foreground">PT </span>
                      <span className="font-semibold">{fmtCurrency(r.priceTarget)}</span>
                    </div>
                  )}
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}

      <ReportDialog
        report={activeReport}
        onClose={() => setActiveReport(null)}
        onOpenCompany={onOpenCompany}
      />
    </div>
  );

  async function openReport(r: Report) {
    try {
      const res = await fetch(`/api/reports/${r.id}`);
      const data = await res.json();
      setActiveReport(data.report);
    } catch {
      setActiveReport(r);
    }
  }
}

function ReportDialog({
  report,
  onClose,
  onOpenCompany,
}: {
  report: Report | null;
  onClose: () => void;
  onOpenCompany: (id: string) => void;
}) {
  return (
    <Dialog open={!!report} onOpenChange={(v) => !v && onClose()}>
      <DialogContent className="max-h-[85vh] sm:max-w-3xl">
        <DialogHeader>
          <DialogTitle className="text-lg">{report?.title}</DialogTitle>
          <DialogDescription className="flex items-center gap-2 text-xs">
            <button
              className="font-mono font-semibold hover:underline"
              onClick={() => report && onOpenCompany(report.company.id)}
            >
              {report?.company.ticker}
            </button>
            <span>·</span>
            <span>{report?.company.name}</span>
            <span>·</span>
            <span>{report && fmtDateTime(report.createdAt)}</span>
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="h-[60vh] pr-4">
          {report?.content ? (
            <article className="prose prose-sm dark:prose-invert max-w-none">
              <ReactMarkdown
                components={{
                  h1: ({ children }) => (
                    <h1 className="mb-3 text-xl font-bold tracking-tight">{children}</h1>
                  ),
                  h2: ({ children }) => (
                    <h2 className="mb-2 mt-5 text-base font-semibold">{children}</h2>
                  ),
                  p: ({ children }) => (
                    <p className="mb-3 text-sm leading-relaxed text-foreground/90">{children}</p>
                  ),
                  ul: ({ children }) => (
                    <ul className="mb-3 ml-4 list-disc space-y-1 text-sm">{children}</ul>
                  ),
                  table: ({ children }) => (
                    <table className="mb-3 w-full border-collapse text-sm">{children}</table>
                  ),
                  th: ({ children }) => (
                    <th className="border border-border bg-muted/50 px-3 py-1.5 text-left text-xs font-medium">
                      {children}
                    </th>
                  ),
                  td: ({ children }) => (
                    <td className="border border-border px-3 py-1.5">{children}</td>
                  ),
                }}
              >
                {report.content}
              </ReactMarkdown>
            </article>
          ) : (
            <div className="text-sm text-muted-foreground">Loading…</div>
          )}
        </ScrollArea>
        {report && (
          <div className="flex items-center justify-between border-t border-border pt-3">
            <Button
              variant="outline"
              size="sm"
              onClick={() => window.print()}
            >
              <FileText className="mr-1.5 h-3.5 w-3.5" /> Export PDF
            </Button>
            <Button
              variant="outline"
              size="sm"
              onClick={async () => {
                try {
                  const res = await fetch("/api/share", {
                    method: "POST",
                    headers: { "Content-Type": "application/json" },
                    body: JSON.stringify({ reportId: report.id }),
                  });
                  if (res.ok) {
                    const data = await res.json();
                    const url = `${window.location.origin}/?share=${data.token}`;
                    await navigator.clipboard.writeText(url);
                    toast.success("Share link copied to clipboard!");
                  }
                } catch {
                  toast.error("Failed to create share link");
                }
              }}
            >
              <Share2 className="mr-1.5 h-3.5 w-3.5" /> Share
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
